### ISSUE TITLE
org.bukkit.material.Sign.getAttachedFace() SOUTH = null

### ISSUE THREAD

**Issue by TominoLP** [PrismarineTeam/Prismarine#15]
### Describe error

Face south of org.bukkit.material.Sign.getAttachedFace() is null 

Nord East West works fine

### Expected result

get blockfacing south

### Actual result

error:
[18:50:12 ERROR]: Could not pass event PlayerInteractEvent to ServerSystem v1.0-SNAPSHOT
[18:50:12 ERROR]: Suspected Plugins:
[18:50:12 ERROR]:       ServerSystem{enabled,ver=1.0-SNAPSHOT,path=plugins\ServerSystem-1.0-SNAPSHOT.jar}
[18:50:12 ERROR]: Exception details below:
java.lang.NullPointerException: Cannot invoke "org.bukkit.block.BlockFace.getOppositeFace()" because the return value of "org.bukkit.material.Sign.getAttachedFace()" is null
        at org.bukkit.material.Sign.getFacing(Sign.java:134) ~[Prismarine-API-1.19.2-R0.1-SNAPSHOT.jar:?]
        at de.tomino.serversystem.displaycase.DisplayCase.onSignUse(DisplayCase.java:195) ~[ServerSystem-1.0-SNAPSHOT.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor6.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[Prismarine-API-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[Prismarine-API-1.19.2-R0.1-SNAPSHOT.jar:git-Prismarine-"279b5a4"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[Prismarine-API-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:689) ~[Prismarine-API-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:534) ~[prismarine-1.19.2.jar:git-Prismarine-"279b5a4"]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:527) ~[prismarine-1.19.2.jar:git-Prismarine-"279b5a4"]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:2050) ~[prismarine-1.19.2.jar:git-Prismarine-"279b5a4"]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[prismarine-1.19.2.jar:git-Prismarine-"279b5a4"]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:9) ~[prismarine-1.19.2.jar:git-Prismarine-"279b5a4"]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[prismarine-1.19.2.jar:git-Prismarine-"279b5a4"]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[prismarine-1.19.2.jar:git-Prismarine-"279b5a4"]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:173) ~[prismarine-1.19.2.jar:git-Prismarine-"279b5a4"]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[prismarine-1.19.2.jar:git-Prismarine-"279b5a4"]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1374) ~[prismarine-1.19.2.jar:git-Prismarine-"279b5a4"]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:185) ~[prismarine-1.19.2.jar:git-Prismarine-"279b5a4"]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:135) ~[prismarine-1.19.2.jar:git-Prismarine-"279b5a4"]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1351) ~[prismarine-1.19.2.jar:git-Prismarine-"279b5a4"]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1344) ~[prismarine-1.19.2.jar:git-Prismarine-"279b5a4"]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:146) ~[prismarine-1.19.2.jar:git-Prismarine-"279b5a4"]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1322) ~[prismarine-1.19.2.jar:git-Prismarine-"279b5a4"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1210) ~[prismarine-1.19.2.jar:git-Prismarine-"279b5a4"]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[prismarine-1.19.2.jar:git-Prismarine-"279b5a4"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### How to reproduce error

                        BlockFace blockFace = ((org.bukkit.material.Sign) s.getData()).getFacing().getOppositeFace();

                        switch (blockFace) {

                            case WEST:
                                blockBehindSign = event.getClickedBlock().getRelative(BlockFace.WEST);
                                facing = "WEST";
                                CreateGui(player);
                                break;

                            case EAST:
                                blockBehindSign = event.getClickedBlock().getRelative(BlockFace.EAST);
                                facing = "EAST";
                                CreateGui(player);
                                break;

                            case NORTH:
                                blockBehindSign = event.getClickedBlock().getRelative(BlockFace.NORTH);
                                facing = "NORTH";
                                CreateGui(player);
                                break;

                            case SOUTH:
                                blockBehindSign = event.getClickedBlock().getRelative(BlockFace.SOUTH);
                                facing = "SOUTH";
                                CreateGui(player);
                                break;

                            default:
                                break;
                        }

### Plugin list

only my plugin

### Datapack list

N/A

### Version of Prismarine

 279b5a4

### JVM Flag

N/A

### JDK Version

Corretto 17

### Operating System (OS)

Windows 11 Pro 

### Before you report, please check once more.

- [X] I'm using the latest Prismarine in this version of Minecraft.
- [X] I checked that this error has not reported yet.
- [X] Prismarine supports this version of Minecraft.

**Comment by TominoLP** [comment]
ahh MaterialData is deprecated sry my bad
